name: Build APK

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleVanillaDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: aurora-updater-debug
        path: app/build/outputs/apk/vanilla/debug/app-vanilla-debug.apk

    - name: Get commit SHA
      id: vars
      run: echo "sha_short=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Create Release (on push to master)
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ steps.vars.outputs.sha_short }}
        name: Aurora Updater Build ${{ steps.vars.outputs.sha_short }}
        body: |
          Automated build from commit ${{ github.sha }}
          
          **Changes in this build:**
          - Simplified Aurora Store focused only on app updates
          - Removed app browsing and search functionality
          - Removed customization settings
          
          Install the APK below to try the latest version.
        files: app/build/outputs/apk/vanilla/debug/app-vanilla-debug.apk
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}